export const memories = [
  {
    id: 1,
    type: "first-year",
    src: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    title: "First Day on Campus, 29 Jan 2023",
    desc: "The beginning of our university journey—unfamiliar faces, new dreams and endless possibilities.",
  },
  {
    id: 2,
    type: "intake_day",
    src: "https://i.ibb.co.com/Pv2VZs4L/1st-intake-day.jpg",
    title: "First Intake Day, 29 Jan 2024",
    desc: "A special day celebrating our journey, growth and the bond we built together as a batch.",
  },
  {
    id: 3,
    type: "intake_day",
    src: "https://i.ibb.co.com/3mBVH5y0/1-intake.jpg",
    title: "1st Intake Day Decoration, 29 Jan 2024",
    desc: "Decorations filled with effort, excitement and pride that made the intake day memorable.",
  },
  {
    id: 4,
    type: "intake_day",
    src: "https://i.ibb.co.com/JFtMW2z1/boys-intake.jpg",
    title: "The Boys, 29 Jan 2024",
    desc: "A moment capturing brotherhood, confidence and the spirit of CSE 14th.",
  },
  {
    id: 5,
    type: "sports_week",
    src: "https://i.ibb.co.com/4wMftLpj/13-er-joy.jpg",
    title: "Victory Against 13th Intake",
    desc: "An exciting cricket match where teamwork and determination led us to victory.",
  },
  {
    id: 6,
    type: "annual_picnic",
    src: "https://i.ibb.co.com/PZM60SkD/annual-picnic-2023.jpg",
    title: "Uttara Gonobhabon, Natore",
    desc: "A joyful picnic filled with laughter, exploration and unforgettable shared moments.",
  },
  {
    id: 9,
    type: "batch_tour",
    src: "https://i.ibb.co.com/7N0x7J05/IMG-20230312-171032-051.jpg",
    title: "Rangpur Zoo",
    desc: "A refreshing tour where we relaxed, explored nature and enjoyed each other’s company.",
  },
  {
    id: 10,
    type: "batch_tour",
    src: "https://i.ibb.co.com/qYZhLx9f/IMG-20230317-201032-974.jpg",
    title: "Tajhat Palace, Rangpur",
    desc: "A cultural visit that blended history, friendship and memorable conversations.",
  },
  {
    id: 11,
    type: "batch_tour",
    src: "https://i.ibb.co.com/WvgF0vrg/IMG-20230321-025227-567.jpg",
    title: "Sena Proyash Binodon Park, Gaghot",
    desc: "A day of fun, laughter, and bonding that strengthened our connection as a batch.",
  },
  {
    id: 12,
    type: "batch_tour",
    src: "https://i.ibb.co.com/KzsbksL1/IMG-20230321-025314-945.jpg",
    title: "Sena Proyash Binodon Park, Gaghot",
    desc: "Another captured moment from one of the happiest and most joyful days of our journey.",
  },
  {
    id: 13,
    type: "ifter",
    src: "https://i.ibb.co.com/kVG9BQgR/IMG-20230330-033144-340.jpg",
    title: "Iftar Together",
    desc: "Sharing iftar together strengthened our bond through faith, friendship and togetherness.",
  },
  {
    id: 14,
    type: "adda",
    src: "https://i.ibb.co.com/G4SL012S/IMG-20230510-141421.jpg",
    title: "Syndicate Meeting",
    desc: "An adda full of discussions, laughter, and memories beyond academic life.",
  },
  {
    id: 15,
    type: "adda",
    src: "https://i.ibb.co.com/sdtmLG97/IMG-20230526-162946.jpg",
    title: "SCL, 2023",
    desc: "Moments of unity, excitement, and pride during one of our favorite campus events.",
  },
  {
    id: 16,
    type: "intake_day",
    src: "https://i.ibb.co.com/JWfYwJST/IMG-20230529-152547.jpg",
    title: "4 Month Celebration, 29 May 2023",
    desc: "Celebrating four months of togetherness, friendship and shared university life.",
  },
  {
    id: 17,
    type: "sports",
    src: "https://i.ibb.co.com/ZpM7LdMw/IMG-20230613-084956.jpg",
    title: "13 vs 14 Friendly Football Match",
    desc: "A friendly match filled with energy, teamwork and sportsmanship.",
  },
  {
    id: 18,
    type: "sports",
    src: "https://i.ibb.co.com/84fP4zXY/IMG-20230613-094352.jpg",
    title: "13 vs 14 Friendly Football Match",
    desc: "Another moment capturing the excitement and unity of the match.",
  },
  {
    id: 19,
    type: "14",
    src: "https://i.ibb.co.com/ymDq0zP8/IMG-20230613-095933.jpg",
    title: "The Number 14",
    desc: "A symbol of identity, pride, and the legacy of our batch.",
  },
  {
    id: 20,
    type: "batch_tour",
    src: "https://i.ibb.co.com/HT8Vk6Tq/IMG-20230718-171027.jpg",
    title: "Way to Mohipur Bridge, Teesta",
    desc: "The journey itself became a memory—roads, laughter and excitement along the way.",
  },
  {
    id: 21,
    type: "batch_tour",
    src: "https://i.ibb.co.com/RT4w4mZ9/IMG-20230718-184248.jpg",
    title: "Mohipur Bridge, Teesta",
    desc: "Standing together by the river, creating moments that felt calm and timeless.",
  },
  {
    id: 22,
    type: "adda",
    src: "https://i.ibb.co.com/tTbWPT3y/IMG-20230827-201640.jpg",
    title: "Planning for 15th Intake Orientation",
    desc: "Late discussions and planning sessions that reflected our responsibility as seniors.",
  },
  {
    id: 23,
    type: "intake_day",
    src: "https://i.ibb.co.com/9HYjV6vr/475880869-602110996078385-16697508387486653-n.jpg",
    title: "6th Month Celebration, 29 Jaly 2024",
    desc: "Celebrating four months of togetherness, friendship and shared university life.",
  },
  {
    id: 24,
    type: "sports",
    src: "https://i.ibb.co.com/5X3zKXRh/481468617-1654031308808477-8010134150209991703-n.jpg",
    title: "CSE Fest 2023",
    desc: "A vibrant moment from CSE Fest 2023, filled with energy, teamwork and the true spirit of celebration.",
  },
  {
    id: 25,
    type: "annual_picnic",
    src: "https://i.ibb.co.com/BHbpYXc8/480858022-1650648405813434-2692110224502453916-n.jpg",
    title: "Panchagarh, 2024",
    desc: "A joyful picnic in Panchagarh during 2024, filled with laughter, exploration and unforgettable shared moments.",
  },
  {
    id: 26,
    type: "batch_picnic",
    src: "https://i.ibb.co.com/svWdjLZt/482225450-1650533179158290-1929707083726560483-n.jpg",
    title: "Batch Picnic Moments",
    desc: "A simple yet memorable picnic where laughter, friendship, and togetherness defined the day.",
  },
  {
    id: 8,
    type: "varsity_program",
    src: "https://i.ibb.co.com/bgXLdwCM/pitha-utshob.jpg",
    title: "Pitha Utshob, 2023",
    desc: "A colorful celebration of tradition, culture and joyful campus life.",
  },
];
