
export const timelineData = [
  {
    title: "Orientation Day",
    date: "29 Jan 2023",
    description:
      "It was the first day of our university life. Everyone was unfamiliar, yet there was a sense of new excitement in the air.",
    align: "right",
    gradientFrom: "from-rose-900/40",
    gradientTo: "to-pink-900/40",
    borderColor: "border-rose-500",
    dotColor: "bg-rose-500",
    badgeColor: "bg-rose-600/80",
    shadowColor: "hover:shadow-rose-500/30",
    glowColor: "bg-rose-500",
  },
  {
    title: "First Tour",
    date: "February, 2023",
    description: "Visiting Carmichael College, Rangpur.",
    align: "left",
    gradientFrom: "from-purple-900/40",
    gradientTo: "to-violet-900/40",
    borderColor: "border-purple-500",
    dotColor: "bg-purple-500",
    badgeColor: "bg-purple-600/80",
    shadowColor: "hover:shadow-purple-500/30",
    glowColor: "bg-purple-500",
  },
  {
    title: "Annual Picnic",
    date: "March, 2023",
    description:
      "Singing songs on the bus and sharing endless laughter made our annual picnic truly special.",
    align: "right",
    gradientFrom: "from-amber-900/40",
    gradientTo: "to-yellow-900/40",
    borderColor: "border-amber-500",
    dotColor: "bg-amber-500",
    badgeColor: "bg-amber-600/80",
    shadowColor: "hover:shadow-amber-500/30",
    glowColor: "bg-amber-500",
  },
  {
    title: "Visiting Rangpur Zoo",
    date: "March, 2023",
    description:
      "Our visit to Rangpur Zoo in March 2023 was a fun and refreshing experience.",
    align: "left",
    gradientFrom: "from-emerald-900/40",
    gradientTo: "to-green-900/40",
    borderColor: "border-emerald-500",
    dotColor: "bg-emerald-500",
    badgeColor: "bg-emerald-600/80",
    shadowColor: "hover:shadow-emerald-500/30",
    glowColor: "bg-emerald-500",
  },
  {
    title: "Tajhat Palace, Rangpur",
    date: "April, 2023",
    description:
      "Our trip to Tajhat Palace, Rangpur was also a fun and refreshing experience.",
    align: "right",
    gradientFrom: "from-sky-900/40",
    gradientTo: "to-blue-900/40",
    borderColor: "border-sky-500",
    dotColor: "bg-sky-500",
    badgeColor: "bg-sky-600/80",
    shadowColor: "hover:shadow-sky-500/30",
    glowColor: "bg-sky-500",
  },
  {
    title: "Sena Proyash Binodon Park, Gaghot",
    date: "April, 2023",
    description:
      "Our trip to Sena Proyash Binodon Park in Gaghot turned out to be one of the most memorable and joyful days of our university life.",
    align: "left",
    gradientFrom: "from-teal-900/40",
    gradientTo: "to-cyan-900/40",
    borderColor: "border-teal-500",
    dotColor: "bg-teal-500",
    badgeColor: "bg-teal-600/80",
    shadowColor: "hover:shadow-teal-500/30",
    glowColor: "bg-teal-500",
  },
  {
    title: "Mohipur Bridge Visit",
    date: "July, 2023",
    description:
      "Our trip to Mohipur Bridge turned out to be one of the most memorable and joyful days of our university life.",
    align: "right",
    gradientFrom: "from-red-900/40",
    gradientTo: "to-orange-900/40",
    borderColor: "border-red-500",
    dotColor: "bg-red-500",
    badgeColor: "bg-red-600/80",
    shadowColor: "hover:shadow-red-500/30",
    glowColor: "bg-red-500",
  },
  {
    title: "6 Months of Intake Day",
    date: "29 July 2023",
    description:
      "Six months into our journey, the unfamiliar slowly turned into friendship, and the campus began to feel like a second home.",
    align: "left",
    gradientFrom: "from-indigo-900/40",
    gradientTo: "to-purple-900/40",
    borderColor: "border-indigo-500",
    dotColor: "bg-indigo-500",
    badgeColor: "bg-indigo-600/80",
    shadowColor: "hover:shadow-indigo-500/30",
    glowColor: "bg-indigo-500",
  },
  {
    title: "Teesta Bridge Visit",
    date: "August 2023",
    description:
      "Our visit to Teesta Bridge was filled with fresh air, shared laughter, and moments that strengthened our bond beyond the classroom.",
    align: "right",
    gradientFrom: "from-blue-900/40",
    gradientTo: "to-cyan-900/40",
    borderColor: "border-blue-500",
    dotColor: "bg-blue-500",
    badgeColor: "bg-blue-600/80",
    shadowColor: "hover:shadow-blue-500/30",
    glowColor: "bg-blue-500",
  },
  {
    title: "One Year of Varsity Life",
    date: "29 Jan 2024",
    description:
      "One year of university life taught us lessons beyond books—friendship, teamwork, and memories that shaped who we became.",
    align: "left",
    gradientFrom: "from-lime-900/40",
    gradientTo: "to-green-900/40",
    borderColor: "border-lime-500",
    dotColor: "bg-lime-500",
    badgeColor: "bg-lime-600/80",
    shadowColor: "hover:shadow-lime-500/30",
    glowColor: "bg-lime-500",
  },
  {
    title: "Picnics Between Deadlines",
    date: "2023 – 2025",
    description:
      "Between deadlines and academic pressure, we arranged many small picnics and outings among ourselves, creating moments of joy that balanced our busy university life.",
    align: "right",
    gradientFrom: "from-orange-900/40",
    gradientTo: "to-amber-900/40",
    borderColor: "border-orange-500",
    dotColor: "bg-orange-500",
    badgeColor: "bg-orange-600/80",
    shadowColor: "hover:shadow-orange-500/30",
    glowColor: "bg-orange-500",
  },
  {
    title: "Two Years of University Life",
    date: "29 Jan 2025",
    description:
      "Completing two years of university life marked a new chapter of maturity, stronger bonds, and unforgettable memories shared together.",
    align: "left",
    gradientFrom: "from-green-900/40",
    gradientTo: "to-emerald-900/40",
    borderColor: "border-green-500",
    dotColor: "bg-green-500",
    badgeColor: "bg-green-600/80",
    shadowColor: "hover:shadow-green-500/30",
    glowColor: "bg-green-500",
  },
  {
    title: "Second Year Celebration Picnic",
    date: "Early 2025",
    description:
      "To celebrate two years of togetherness, we arranged a picnic filled with laughter, stories, and moments that reminded us how far we had come as a batch.",
    align: "right",
    gradientFrom: "from-yellow-900/40",
    gradientTo: "to-orange-900/40",
    borderColor: "border-yellow-500",
    dotColor: "bg-yellow-500",
    badgeColor: "bg-yellow-600/80",
    shadowColor: "hover:shadow-yellow-500/30",
    glowColor: "bg-yellow-500",
  },
  {
    title: "Events, Sports & Endless Memories",
    date: "2023 – 2025",
    description:
      "We arranged many events and picnics, including our batch futsal tournament full of excitement and fun. From player auctions to endless cheering, these memories go on to infinity.",
    align: "left",
    gradientFrom: "from-fuchsia-900/40",
    gradientTo: "to-pink-900/40",
    borderColor: "border-fuchsia-500",
    dotColor: "bg-fuchsia-500",
    badgeColor: "bg-fuchsia-600/80",
    shadowColor: "hover:shadow-fuchsia-500/30",
    glowColor: "bg-fuchsia-500",
  },
];